### ISSUE TITLE
An incredible Tool ! Thank you. Hope you have time to add support to export music libraries.

### ISSUE THREAD

**Issue by moutasem1989** [van-geaux/plex_nfo_exporter#2]
I had an internet outage for a couple of weeks and plex was not accessible the normal way because of its dependence on Plex authentication services. So I am trying to move away from plex and into Jellyfin!
your tool was so incredibly helpful moving all the information I manually added to videos over the last decade.

I do have still audio libraries with custom posters, album data and other metadata I manually added that I need exported as well. I tried your tool for that but it was not successful sadly. Can you help with that ?

**Comment by van-geaux** [comment]
Glad it is of help for you :)

I have never used plex for audio libraries so I don't know what a good audio library and their metadata looks like. Can you send 2 or 3 samples of these so I can look over them:

1. Screenshots of what the library structure looks like (library-album-song?)
2. Xml of the media ([how to](https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/))
3. Metadata of library outside plex (or link to a documentation/article of good audio library metadata)
4. Your opinion on which items needs to be in the metadata and which items are optional

**Comment by moutasem1989** [comment]
I used the [Plex Guid](https://support.plex.tv/articles/200265296-adding-music-media-from-folders/) to name the Music library: `Music/ArtistName/AlbumName/TrackNumber - TrackName.ext`. This very similar to the way [Jellyfin](https://jellyfin.org/docs/general/server/media/music/) organise Music Libraries. [Navidrome](https://www.navidrome.org/) for example does not care about the structure much.
The library looks like this with the option to view Artist, Album, Tracks:

![IMG_0269](https://github.com/user-attachments/assets/128ca1e1-6776-4be6-894b-e4a6955da941)

Individual files have an XML similar to [this](https://raw.githubusercontent.com/moutasem1989/Share/refs/heads/main/109397.xml). I could not find out if Artists or Albums have similar information. I did however find this [repository](https://github.com/bradleyfrank/plexport). I think album/artist information are most needed. Everything else is optional.

Found the following regarding music metadata:
https://soundcharts.com/blog/music-metadata
Metadata can be embedded into the files or saved as INFO file. Also found this [Py library](https://pypi.org/project/audio-metadata/).

**Comment by van-geaux** [comment]
Done, sorry it took a while, I know nothing about music. I tested it with some random artists and albums and it works fine on mine. There are "mood" metadata in plex but I ommit them from the nfo because jellyfin is not supporting them anyway.
